====
Starting job 4785742 at Wed 19 Jan 18:17:43 GMT 2022 for user dc-wils7.
Running on nodes: m5399
====

Environment:

Code: /cosma/home/durham/dc-wils7/DESI/
Gold output dir.: /cosma5/data/durham/dc-wils7/GAMA4/
Randoms output dir: /cosma5/data/durham/dc-wils7/GAMA4/randoms/
Traceback (most recent call last):
  File "/cosma/home/durham/dc-wils7/DESI/gen_ddp_n8.py", line 28, in <module>
    dat    = Table.read(fpath)
  File "/cosma/home/durham/dc-wils7/.local/lib/python3.9/site-packages/astropy/table/connect.py", line 62, in __call__
    out = self.registry.read(cls, *args, **kwargs)
  File "/cosma/home/durham/dc-wils7/.local/lib/python3.9/site-packages/astropy/io/registry/core.py", line 184, in read
    fileobj = ctx.__enter__()
  File "/cosma/home/durham/dc-wils7/.conda/envs/lumfn/lib/python3.9/contextlib.py", line 119, in __enter__
    return next(self.gen)
  File "/cosma/home/durham/dc-wils7/.local/lib/python3.9/site-packages/astropy/utils/data.py", line 271, in get_readable_fileobj
    fileobj = io.FileIO(name_or_obj, 'r')
FileNotFoundError: [Errno 2] No such file or directory: '/cosma5/data/durham/dc-wils7/GAMA4//gama_gold_ddp_dryrun.fits'
Traceback (most recent call last):
  File "/cosma/home/durham/dc-wils7/DESI/gen_gold_lf.py", line 108, in <module>
    rand = Table.read(rpath)
  File "/cosma/home/durham/dc-wils7/.local/lib/python3.9/site-packages/astropy/table/connect.py", line 62, in __call__
    out = self.registry.read(cls, *args, **kwargs)
  File "/cosma/home/durham/dc-wils7/.local/lib/python3.9/site-packages/astropy/io/registry/core.py", line 184, in read
    fileobj = ctx.__enter__()
  File "/cosma/home/durham/dc-wils7/.conda/envs/lumfn/lib/python3.9/contextlib.py", line 119, in __enter__
    return next(self.gen)
  File "/cosma/home/durham/dc-wils7/.local/lib/python3.9/site-packages/astropy/utils/data.py", line 271, in get_readable_fileobj
    fileobj = io.FileIO(name_or_obj, 'r')
FileNotFoundError: [Errno 2] No such file or directory: '/cosma5/data/durham/dc-wils7/GAMA4/randoms//randoms_bd_ddp_n8_G9_0_dryrun.fits'
Traceback (most recent call last):
  File "/cosma/home/durham/dc-wils7/DESI/gen_gold_lf.py", line 108, in <module>
    rand = Table.read(rpath)
  File "/cosma/home/durham/dc-wils7/.local/lib/python3.9/site-packages/astropy/table/connect.py", line 62, in __call__
    out = self.registry.read(cls, *args, **kwargs)
  File "/cosma/home/durham/dc-wils7/.local/lib/python3.9/site-packages/astropy/io/registry/core.py", line 184, in read
    fileobj = ctx.__enter__()
  File "/cosma/home/durham/dc-wils7/.conda/envs/lumfn/lib/python3.9/contextlib.py", line 119, in __enter__
    return next(self.gen)
  File "/cosma/home/durham/dc-wils7/.local/lib/python3.9/site-packages/astropy/utils/data.py", line 271, in get_readable_fileobj
    fileobj = io.FileIO(name_or_obj, 'r')
FileNotFoundError: [Errno 2] No such file or directory: '/cosma5/data/durham/dc-wils7/GAMA4/randoms//randoms_bd_ddp_n8_G12_0_dryrun.fits'
Traceback (most recent call last):
  File "/cosma/home/durham/dc-wils7/DESI/gen_gold_lf.py", line 108, in <module>
    rand = Table.read(rpath)
  File "/cosma/home/durham/dc-wils7/.local/lib/python3.9/site-packages/astropy/table/connect.py", line 62, in __call__
    out = self.registry.read(cls, *args, **kwargs)
  File "/cosma/home/durham/dc-wils7/.local/lib/python3.9/site-packages/astropy/io/registry/core.py", line 184, in read
    fileobj = ctx.__enter__()
  File "/cosma/home/durham/dc-wils7/.conda/envs/lumfn/lib/python3.9/contextlib.py", line 119, in __enter__
    return next(self.gen)
  File "/cosma/home/durham/dc-wils7/.local/lib/python3.9/site-packages/astropy/utils/data.py", line 271, in get_readable_fileobj
    fileobj = io.FileIO(name_or_obj, 'r')
FileNotFoundError: [Errno 2] No such file or directory: '/cosma5/data/durham/dc-wils7/GAMA4/randoms//randoms_bd_ddp_n8_G15_0_dryrun.fits'

Done.
