====
Starting job 4785735 at Wed 19 Jan 18:17:13 GMT 2022 for user dc-wils7.
Running on nodes: m5350
====
RESET SET TO BE 0

Environment:

Code: /cosma/home/durham/dc-wils7/DESI/
Gold output dir.: /cosma5/data/durham/dc-wils7/GAMA4/
Randoms output dir: /cosma5/data/durham/dc-wils7/GAMA4/randoms/
Running gold pipeline; logging to logs/gama_gold.log
Running gen_kEcat.py; logging to logs/gama_kE.log
Running gen_zmax_cat.py; logging to logs/gama_zama.log
Running ddp_limits.py; logging to logs/ddp_limits.log
Running gen_ddp_cat.py; logging to logs/gama_ddp.log
Running gen_gold_lf.py; logging to logs/gama_lumfn.log
Traceback (most recent call last):
  File "/cosma/home/durham/dc-wils7/DESI/gen_gold_lf.py", line 94, in <module>
    process_cat(fpath, opath, rand=None)
  File "/cosma/home/durham/dc-wils7/DESI/gen_gold_lf.py", line 24, in process_cat
    gama_zmax = Table.read(fpath)
  File "/cosma/home/durham/dc-wils7/.local/lib/python3.9/site-packages/astropy/table/connect.py", line 62, in __call__
    out = self.registry.read(cls, *args, **kwargs)
  File "/cosma/home/durham/dc-wils7/.local/lib/python3.9/site-packages/astropy/io/registry/core.py", line 184, in read
    fileobj = ctx.__enter__()
  File "/cosma/home/durham/dc-wils7/.conda/envs/lumfn/lib/python3.9/contextlib.py", line 119, in __enter__
    return next(self.gen)
  File "/cosma/home/durham/dc-wils7/.local/lib/python3.9/site-packages/astropy/utils/data.py", line 271, in get_readable_fileobj
    fileobj = io.FileIO(name_or_obj, 'r')
FileNotFoundError: [Errno 2] No such file or directory: '/cosma5/data/durham/dc-wils7/GAMA4//gama_gold_zmax_dryrun.fits'

Done.
